language: node_js
node_js:
  - 7
  - 8
  - 9
before_script: npm install
script: npm run test-all
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
